<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="MobileAutomation.MobileSeeTestWebAutomation.TestLoginLogout" tests="1" time="64.670" ignored="4" failures="0" timestamp="03 Jun 2021 06:56:31 GMT" skipped="0" hostname="LAPTOP-2HJFJ1OT" errors="1">
  <testcase name="testLoginFeature" time="64.670" classname="MobileAutomation.MobileSeeTestWebAutomation.TestLoginLogout">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
	at Resources.Base.tearDown(Base.java:58)
	at Resources.FunctionalComponents.clickMenuButton(FunctionalComponents.java:156)
	at MobileAutomation.MobileSeeTestWebAutomation.TestLoginLogout.testLoginFeature(TestLoginLogout.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testLoginFeature -->
  <testcase name="testLocationFeature" classname="MobileAutomation.MobileSeeTestWebAutomation.TestLoginLogout">
    <skipped/>
  </testcase> <!-- testLocationFeature -->
  <testcase name="testFavouriteItems" classname="MobileAutomation.MobileSeeTestWebAutomation.TestLoginLogout">
    <skipped/>
  </testcase> <!-- testFavouriteItems -->
  <testcase name="testRewardsFeature" classname="MobileAutomation.MobileSeeTestWebAutomation.TestLoginLogout">
    <skipped/>
  </testcase> <!-- testRewardsFeature -->
  <testcase name="testUpdateAccountFeature" classname="MobileAutomation.MobileSeeTestWebAutomation.TestLoginLogout">
    <skipped/>
  </testcase> <!-- testUpdateAccountFeature -->
</testsuite> <!-- MobileAutomation.MobileSeeTestWebAutomation.TestLoginLogout -->
